let dtgrammar = {
  meals: [
    "burger",
    "chicken sandwich",
    "fries",
    "nuggets",
    "hot dog",
    "salad",
    "burrito",
    "taco",
    "sub"
  ],
  adjGood: [
    "crispy",
    "tender",
    "juicy",
    "homestyle",
    "finger lickin'",
    "mouth watering",
    "crunchy",
    "spicy",
    "low calorie",
    "delicious",
    "Nashville Hot",
    "authentic",
    "premium quality",
    "organic"
  ],
  adjSus: [
    "slightly expired",
    "six degrees below room temp",
    "questionably sourced",
    "almost sentient",
    "health inspection violating",
    "soggy",
    "carcinogenic",
    "stale",
    "intoxicating but not in a good way",
    "concerningly discolored",
    "isotope emitting",
    "cold at the center",
    "cursed",
    "metallic tasting",
    "slightly fishy"
  ],
  insults: [
      "sheep",
      "fool",
      "simpleton",
      "degenerate",
      "absolute buffoon",
      "scoundrel",
      "peasant",
      "pea brain",
      "lil stinker",
      "plebeian",
      "heathen",
      "barbarian",
      "poopoo head",
      "egg",
      "scum"
  ],
  responsibilities: [
      "mouths to feed",
      "bills to pay",
      "people using my netflix account",
      "debts to settle",
      "dreams to pursue",
      "to escape the capitalist hell I live in",
      "a prophecy to fulfill",
      "to spearhead the next social revolution",
      "to reach enlightement",
      "a crippling fear of dissapointing those around me",
      "only two minutes left of this shift",
      "destructive tendencies",
      "six days left to live" ,
      "to do the homework I've been putting off",
      "to attend my daughter's dance recital",
      "to attain eudaimonia",
      "to end this cycle of suffering" 
  ],
  rejectionStarter: [
      "I'm begging you",
      "Please sir",
      "I implore you",
      "Cmon man",
      "Dawg please",
      "Spare me",
      "I beseech of thee",
      "You don't want to know what will happen",
      "Don't be stupid",
      "This is for the best",
      "I know what's good around here",
      "Listen buddy, I got some friends in some high places",
      "Help a fella out",
      "You can't do this to me",
      "Homie",
      "I can't leave until you do this",
      "The manager forces a quota of these"
  ],
  nameStart: [
    "Mc",
    "In and ",
    "Panda ",
    "Taco ",
    "Kentucky fried ",
    "Raising ",
    "Five ",
    "Olive ",
    "Papa ",
    "Chick ",
    "Buffalo Wild ",
    "Jack in the "
  ],
  nameEnd: [
    "Donalds",
    "Express",
    "Bell",
    "Way",
    "Canes",
    "Guys",
    "Fil-a",
    "Garden",
    "Shack",
    "Station",
    "Grill",
    "Box"
  ]
};
